 SUBROUTINE RICHARDS
 USE BASIC
 USE POINT
 USE MATRIX
 IMPLICIT NONE
 INTEGER :: I,J,K,N,FACE_NUM
 INTEGER :: IK,JK,KK,K1,K2
 INTEGER :: NK,NI,NJ
 REAL (KIND = 8) :: ERRO1,RESK,H_PRESS,H0,HR,ALPHA,A,X0,Y0
 REAL (KIND = 8) :: KTH1,KS1,BZ0,KR,M_SUM,CR,MR,PP,PH1,PH2,KTH2,KTH3,PH3
 REAL (KIND = 8) :: ZMAX,ZMIN,XK,BZ_WELL
 REAL (KIND = 8), ALLOCATABLE :: M_LOCAL(:)
 REAL (KIND = 8), ALLOCATABLE :: K_FACE(:)
 INTEGER :: IL,II,JJ
 INTEGER :: I_INDEX,FLAG_I
 INTEGER, ALLOCATABLE :: F_LINK(:)
 TYPE (FACE_CAL_COR), ALLOCATABLE :: LINE_COR(:)
 REAL (KIND = 8) :: KTH(2,2)
 REAL (KIND = 8) :: MTH,CTH
 REAL (KIND = 8), ALLOCATABLE :: VX(:),VY(:)
 REAL (KIND = 8) :: P_COE(3)

 ERRO1 = 1.0
 
 DO K = 1,FACE_TOT
	IF (FACE_COE(K)%POINT_BC.EQ.1) THEN 
		NK = FACE_COE(K)%BC_NUM
		II = H_INPUT(NK)%DEG
		JJ = 1; FACE_COE(K)%P = 0.0
		IF (II.EQ.(-1)) THEN 
			HR = H_INPUT(NK)%H_COE(1); A = H_INPUT(NK)%H_COE(2)
			ALPHA = H_INPUT(NK)%H_COE(3)
 			H0 = 1.0-EXP(ALPHA*HR)
 			FACE_COE(K)%P = FACE_COE(K)%Y+LOG(EXP(ALPHA*HR)+  &
 			H0/2.0*(1.0-COS(2.0*3.1415926*FACE_COE(K)%X/A)))/ALPHA
 		!	FACE_COE(K)%P = FACE_COE(K)%YC+LOG(EXP(ALPHA*HR)+  &
 		!	H0*SIN(3.1415926*FACE_COE(K)%XC/A))/ALPHA
		ELSE 
			DO IK = 0,II
				DO JK = 0,II-IK
					FACE_COE(K)%P = ((FACE_COE(K)%X)**IK)*((FACE_COE(K)%Y)**JK)*H_INPUT(NK)%H_COE(JJ)+ &
							FACE_COE(K)%P
					JJ = JJ+1
				END DO
			END DO
		END IF
	END IF
 END DO
 
 DO K = 1,FACE_TOT
 	FACE_COE(K)%PN = FACE_COE(K)%P
 END DO
 
 IL = 0
 
 DO WHILE (ABS(ERRO1).GE.ERRO.AND.IL.LE.INTER_CONTROL)
	DO K = 1,FACE_TOT
		FACE_COE(K)%XYZ_P = 0.0; FACE_COE(K)%COE_L = 0.0; FACE_COE(K)%COE_U = 0.0
		FACE_COE(K)%BZ = 0.0
	END DO
	
	DO K = 1,CELL_TOT
		IF (CELL_COE(K)%POINT_TYPE.NE.(-1)) THEN 
			FACE_NUM = CELL_COE(K)%POINT_SIZE
		!	BZ0 = (CELL_COE(K)%MTH-CELL_COE(K)%MTHN-CELL_COE(K)%CTH*CELL_COE(K)%HTH &
		!	      -CELL_COE(K)%MTHN/CELL_COE(K)%THETAS*CELL_COE(K)%SS*CELL_COE(K)%HTHN)/DT*CELL_COE(K)%CELL_V
			
			DO IK = 1,FACE_NUM
				NK = CELL_COE(K)%POINT_INDEX(IK)
		!		BZ0 = (CELL_COE(K)%MTH-CELL_COE(K)%MTHN-CELL_COE(K)%CTH*FACE_COE(NK)%P &
		!	      	     -CELL_COE(K)%MTHN/CELL_COE(K)%THETAS*CELL_COE(K)%SS*FACE_COE(NK)%P_OLD)/DT*CELL_COE(K)%CELL_V
				BZ0 = -CELL_COE(K)%SS*FACE_COE(NK)%P_OLD/DT*CELL_COE(K)%CELL_V/(FACE_NUM*1.0)
		!		M_SUM = (CELL_COE(K)%CTH+CELL_COE(K)%MTHN/CELL_COE(K)%THETAS*CELL_COE(K)%SS)/DT*CELL_COE(K)%CELL_V
				M_SUM = CELL_COE(K)%SS/DT*CELL_COE(K)%CELL_V/(FACE_NUM*1.0)
				IF (CELL_COE(K)%SINGULAR_FLAG.NE.0) THEN 
					KK = CELL_COE(K)%SINGULAR_FLAG
					BZ0 = BZ0-QWELL(KK)/(WELL_CELL_NUM(KK)*1.0)*CELL_COE(K)%SHAPE_COE(IK)
				END IF
				ALLOCATE (F_LINK(FACE_NUM))
				F_LINK = 0
				DO JK = 1,FACE_NUM
					DO II = 1,FACE_COE(NK)%C_SIZE
						IF (CELL_COE(K)%POINT_INDEX(JK).EQ.FACE_COE(NK)%C_INDEX(II)) THEN 
							F_LINK(JK) = II
						END IF
					END DO
				END DO
				DO JK = 1,FACE_NUM
					I = F_LINK(JK)
					FACE_COE(NK)%XYZ_P(I) = FACE_COE(NK)%XYZ_P(I)+CELL_COE(K)%MCF(IK,JK)   !*CELL_COE(K)%KTH
				END DO
				
				FACE_COE(NK)%XYZ_P(1) = FACE_COE(NK)%XYZ_P(1)+M_SUM
				FACE_COE(NK)%BZ = FACE_COE(NK)%BZ-BZ0
				IF (FACE_COE(NK)%POINT_BC.EQ.2) THEN 
					IF (IK.EQ.1) THEN 
						JK = FACE_NUM
					ELSE 
						JK = IK-1
					END IF
					KK = FACE_COE(NK)%BC_NUM
					XK = (QBX(KK)*CELL_COE(K)%NX(IK)*0.5+QBY(KK)*CELL_COE(K)%NY(IK)*0.5)* &
					     CELL_COE(K)%AREA(IK)
					XK = XK+(QBX(KK)*CELL_COE(K)%NX(JK)*0.5+QBY(KK)*CELL_COE(K)%NY(JK)*0.5)* &
					     CELL_COE(K)%AREA(JK)
					FACE_COE(NK)%BZ = FACE_COE(NK)%BZ-XK
				END IF
				DEALLOCATE (F_LINK)
			END DO	
		END IF
	END DO
	DO K = 1,FACE_TOT
		IF (ABS(FACE_COE(K)%XYZ_P(1)).LT.1.0E-10.OR.FACE_COE(K)%POINT_BC.EQ.(-1)) THEN 
			FACE_COE(K)%XYZ_P(1) = 1.0
			NK = FACE_COE(K)%C_SIZE
			DO JK = 2,NK
				FACE_COE(K)%XYZ_P(JK) = 0.0
			END DO
			FACE_COE(K)%BZ = FACE_COE(K)%PN
		ELSE 
			DO JK = 2,FACE_COE(K)%C_SIZE
				NK = FACE_COE(K)%C_INDEX(JK)
				IF (FACE_COE(NK)%POINT_BC.EQ.1) THEN 
					FACE_COE(K)%BZ = FACE_COE(K)%BZ-FACE_COE(NK)%P*FACE_COE(K)%XYZ_P(JK)
					FACE_COE(K)%XYZ_P(JK) = 0.0
				END IF
			END DO
		END IF	
	END DO
	DO K = 1,FACE_TOT
		IF (FACE_COE(K)%POINT_BC.EQ.1) THEN 
			NK = FACE_COE(K)%C_SIZE
			DO JK = 1,NK
				FACE_COE(K)%XYZ_P(JK) = 0.0
			END DO
		END IF
	END DO
	
!	IF (NCYC.EQ.1.AND.IL.EQ.0) THEN 
!		OPEN (11,FILE = 'COE.DAT')
!		DO K = 1,FACE_TOT
!			IF (FACE_COE(K)%POINT_BC.NE.1) THEN 
!				NK = FACE_COE(K)%C_SIZE
!				WRITE (11,'(2I10,20F20.10)') K,FACE_COE(K)%POINT_BC,(FACE_COE(K)%XYZ_P(IK),IK=1,NK),FACE_COE(K)%BZ
!			END IF
!		END DO
!		CLOSE (11)
!	END IF

	CALL PERCON
	
	CALL CG
	ERRO1 = 0.0; I_INDEX = 1

	DO K = 1,FACE_TOT
		IF (FACE_COE(K)%POINT_BC.NE.1) THEN 
			IF (ABS(FACE_COE(K)%PN).GT.1.0) THEN 
				RESK = ABS(FACE_COE(K)%P-FACE_COE(K)%PN)/FACE_COE(K)%PN
			ELSE 
				RESK = ABS(FACE_COE(K)%P-FACE_COE(K)%PN)
			END IF
			IF (RESK.GT.ERRO1) THEN 
				I_INDEX = K
			END IF
		!	WRITE (*,*) K,ERRO1,RESK,FACE_COE(K)%P,FACE_COE(K)%PN
			ERRO1 = MAX(RESK,ERRO1)
		END IF
	END DO
	IL = IL+1
	WRITE (*,*) 'SWEEP, RESL = ',ERRO1,I_INDEX,FACE_COE(I_INDEX)%P
!	IF (NCYC.EQ.474) WRITE (*,*) 'X = ',FACE_COE(I_INDEX)%XC,'Y = ',FACE_COE(I_INDEX)%YC
	IF (IL.GT.INTER_CONTROL) THEN 
		WRITE (*,*) 'CHECK = ',ERRO1
	END IF 

	DO K = 1,CELL_TOT
		FACE_NUM = CELL_COE(K)%POINT_SIZE
		DO IK = 1,FACE_NUM
			KK = CELL_COE(K)%POINT_INDEX(IK)
			ZMAX = 1.0; ZMIN = 1.0
			IF (UIT.EQ.1) THEN 
				call vg(MTH,ZMAX,CTH,FACE_COE(KK)%P-FACE_COE(KK)%Y, &
				CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
				call vg(MTH,ZMIN,CTH,FACE_COE(KK)%PN-FACE_COE(KK)%Y, &
				CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
			END IF
			IF (UIT.EQ.3) THEN 
				call gardner(MTH,ZMAX,CTH,FACE_COE(KK)%P-FACE_COE(KK)%Y, &
				CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
				call gardner(MTH,ZMIN,CTH,FACE_COE(KK)%PN-FACE_COE(KK)%Y, &
				CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
			END IF
			XK = ZMAX/ZMIN
			DO WHILE (XK.GT.10000.0)  
			!	MTH = MTH+CTH*(FACE_COE(KK)%P-FACE_COE(KK)%PN)
			!	IF (UIT.EQ.1) THEN 
			!		CALL VG_INV(H_PRESS,MTH,CELL_COE(K)%THETAS, &
			!		CELL_COE(K)%THETAR,CELL_COE(K)%ALPHA,CELL_COE(K)%M2)
			!	END IF
				
			!	IF (UIT.EQ.3) THEN 
			!		CALL gardner_inv(H_PRESS,MTH,CELL_COE(K)%THETAS, &
			!		CELL_COE(K)%THETAR,CELL_COE(K)%ALPHA,CELL_COE(K)%M2)
			!	END IF
			!	WRITE (*,*) KK,XK,FACE_COE(KK)%P,FACE_COE(KK)%YC+H_PRESS
			!	FACE_COE(KK)%P = FACE_COE(KK)%YC+H_PRESS
				FACE_COE(KK)%P = 0.5*(FACE_COE(KK)%P+FACE_COE(KK)%PN)
				IF (UIT.EQ.1) THEN 
					call vg(MTH,ZMAX,CTH,FACE_COE(KK)%P-FACE_COE(KK)%Y, &
					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
					call vg(MTH,ZMIN,CTH,FACE_COE(KK)%PN-FACE_COE(KK)%Y, &
					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
				END IF
				IF (UIT.EQ.3) THEN 
					call gardner(MTH,ZMAX,CTH,FACE_COE(KK)%P-FACE_COE(KK)%Y, &
					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
					call gardner(MTH,ZMIN,CTH,FACE_COE(KK)%PN-FACE_COE(KK)%Y, &
					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
				END IF
				XK = ZMAX/ZMIN
			END DO
		END DO
	END DO
	!WRITE (*,*) FACE_COE(I_INDEX)%P
	DO K = 1,FACE_TOT
		FACE_COE(K)%PN = FACE_COE(K)%P
	END DO
! Update the cell center head
	DO K = 1,CELL_TOT
		IF (CELL_COE(K)%POINT_TYPE.NE.(-1)) THEN 
			FACE_NUM = CELL_COE(K)%POINT_SIZE
			
			CELL_COE(K)%HTH = 0.0
			M_SUM = 0.0
			DO IK = 1,FACE_NUM
				KK = CELL_COE(K)%POINT_INDEX(IK)
				M_SUM = FACE_COE(KK)%P+M_SUM			
			END DO
			CELL_COE(K)%HTH = M_SUM/(FACE_NUM*1.0)
		END IF
	END DO	

! Update soil properties (cell center)
	DO K = 1,CELL_TOT
	IF (CELL_COE(K)%POINT_TYPE.NE.(-1)) THEN 
 		IF (UIT.EQ.1) THEN 
 			call vg(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,CELL_COE(K)%HTH-CELL_COE(K)%Y, &
 				CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 		END IF
 		IF (UIT.EQ.2) THEN 
 			call Haverkamp(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,CELL_COE(K)%HTH-CELL_COE(K)%Y,&
 			     CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%A,CELL_COE(K)%M2,CELL_COE(K)%B)
 		END IF
 		IF (UIT.EQ.3) THEN 
 			call gardner(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,CELL_COE(K)%HTH-CELL_COE(K)%Y,&
 			     	     CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 		END IF
 		IF (K_SCHEME.EQ.1) THEN ! Cell Center 
 			CELL_COE(K)%KTH = KTH1
 		END IF
 		IF (K_SCHEME.NE.1) THEN 
 			FACE_NUM = CELL_COE(K)%POINT_SIZE
 			ALLOCATE (K_FACE(FACE_NUM))
 			DO IK = 1,FACE_NUM
 				KK = CELL_COE(K)%POINT_INDEX(IK)
 				PH1 = FACE_COE(KK)%P-FACE_COE(KK)%Y
 				IF (UIT.EQ.1) THEN 
 					call vg(MTH,KTH1,CTH,PH1, &
 					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 				END IF
 				IF (UIT.EQ.2) THEN 
 					call Haverkamp(MTH,KTH1,CTH,PH1,&
 					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%A,CELL_COE(K)%M2,CELL_COE(K)%B)
 				END IF
 				IF (UIT.EQ.3) THEN 
 					call gardner(MTH,KTH1,CTH,PH1,&
 					CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 				END IF
 				K_FACE(IK) = KTH1
 			END DO
 			KR = 0.0; M_SUM = 0.0
 			FLAG_I = 0
 			DO IK = 1,FACE_NUM
 				IF (K_SCHEME.EQ.2) THEN   ! GEOMETRIC MEAN minimize Frobenius norm
 					KR = KR+LOG(ABS(K_FACE(IK)))*CELL_COE(K)%FA_COE(IK)
 					M_SUM = M_SUM+CELL_COE(K)%FA_COE(IK)
 				END IF
 				IF (K_SCHEME.EQ.3) THEN ! Arithmetic Mean minimize Frobenius norm
 					KR = KR+K_FACE(IK)*CELL_COE(K)%FA_COE(IK)
 				!	KR = KR+K_FACE(IK)
 					M_SUM = M_SUM+CELL_COE(K)%FA_COE(IK)
 				!	M_SUM = M_SUM+1.0
 				END IF
 				IF (K_SCHEME.EQ.4) THEN ! POWER MEAN
 					KR = KR+SQRT(ABS(K_FACE(IK)))*CELL_COE(K)%FA_COE(IK)
 					M_SUM = M_SUM+CELL_COE(K)%FA_COE(IK)
 				END IF
 			END DO
 			IF (K_SCHEME.EQ.2) THEN
 				CELL_COE(K)%KTH = EXP(KR/M_SUM)
 			END IF
 			IF (K_SCHEME.EQ.3) THEN 
 				CELL_COE(K)%KTH = KR/M_SUM
 			END IF
 			IF (K_SCHEME.EQ.4) THEN 
 				CELL_COE(K)%KTH = (KR/M_SUM)**2
 			END IF
 			DEALLOCATE (K_FACE)
 		END IF
 	END IF
 	END DO 	
 END DO
 
 DO K = 1,CELL_TOT
 	CELL_COE(K)%HTHN = CELL_COE(K)%HTH
 	CELL_COE(K)%MTHN = CELL_COE(K)%MTH
 END DO
 DO K = 1,FACE_TOT
 	FACE_COE(K)%PN = FACE_COE(K)%P
 	FACE_COE(K)%P_OLD = FACE_COE(K)%P
 END DO
 
! Compute Velocity on each edge
 DO K = 1,CELL_TOT
 	IF (CELL_COE(K)%POINT_TYPE.NE.(-1)) THEN 	
 		FACE_NUM = CELL_COE(K)%POINT_SIZE
 		P_COE = 0.0
 		DO IK = 1,FACE_NUM
 			KK = CELL_COE(K)%POINT_INDEX(IK)
 			P_COE(2) = P_COE(2)+CELL_COE(K)%RRNC(2,IK)*FACE_COE(KK)%P
 			P_COE(3) = P_COE(3)+CELL_COE(K)%RRNC(3,IK)*FACE_COE(KK)%P
 		END DO		
 		CELL_COE(K)%VX = (P_COE(2)*CELL_COE(K)%K_S(1,1)+P_COE(3)*CELL_COE(K)%K_S(1,2))   !*CELL_COE(K)%KTH
 		CELL_COE(K)%VY = (P_COE(2)*CELL_COE(K)%K_S(2,1)+P_COE(3)*CELL_COE(K)%K_S(2,2))   !*CELL_COE(K)%KTH
 	END IF
 END DO
 
 END SUBROUTINE 
 
 SUBROUTINE EIGEN_K(X0,Y0,LINE_NUM,LINE_COR,K_FACE,KTH1)
 USE POINT 
 IMPLICIT NONE 
 INTEGER :: LINE_NUM
 TYPE (FACE_CAL_COR) :: LINE_COR(LINE_NUM)
 INTEGER :: IK,JK,KK
 INTEGER :: K1,K2,I,J,K
 REAL (KIND = 8) :: RH_INT,XK
 REAL (KIND = 8) :: KTH(2,2)
 REAL (KIND = 8) :: K_FACE(LINE_NUM)
 REAL (KIND = 8) :: NC(LINE_NUM,2),RC(LINE_NUM,2),RNC(2,2)
 REAL (KIND = 8) :: NX,NY,X0,Y0,X1,Y1,X2,Y2
 REAL (KIND = 8) :: NX0,NY0,NX1,NY1,LLX,LLY,LL
 REAL (KIND = 8) :: LAMDA1,LAMDA2,A1,A2,B1,B2
 REAL (KIND = 8) :: CELL_V
 REAL (KIND = 8) :: COE(2,2)
 REAL (KIND = 8) :: KTH1
 REAL (KIND = 8) :: LAM(2)
 
 KTH = 0.0
 KTH(1,1) = 1.0; KTH(2,2) = 1.0
 
 DO IK = 1,LINE_NUM
 	LINE_COR(IK)%NODE_XYZ(1,1) = LINE_COR(IK)%NODE_XYZ(1,1)-X0
 	LINE_COR(IK)%NODE_XYZ(1,2) = LINE_COR(IK)%NODE_XYZ(1,2)-Y0
 	
 	LINE_COR(IK)%NODE_XYZ(2,1) = LINE_COR(IK)%NODE_XYZ(2,1)-X0
 	LINE_COR(IK)%NODE_XYZ(2,2) = LINE_COR(IK)%NODE_XYZ(2,2)-Y0
 END DO
 
 X0 = 0.0; Y0 = 0.0
 NC = 0.0; RC = 0.0
 CELL_V = 0.0
 DO IK = 1,LINE_NUM
 	X1 = LINE_COR(IK)%NODE_XYZ(1,1); Y1 = LINE_COR(IK)%NODE_XYZ(1,2)
 	X2 = LINE_COR(IK)%NODE_XYZ(2,1); Y2 = LINE_COR(IK)%NODE_XYZ(2,2)
 	
 	NX = X2-X1; NY = Y2-Y1
 	LL = SQRT(NX*NX+NY*NY)
 	NX = NX/LL; NY = NY/LL
 	
 	NX1 = -NY; NY1 = NX
 	NX0 = -X0+0.5*(X1+X2); NY0 = -Y0+0.5*(Y1+Y2)
 	
 	LLX = NX1*NX0+NY1*NY0
 	IF (LLX.LT.0.0) THEN 
 		NX1 = -NX1; NY1 = -NY1
 	END IF
 	
 	XK = KTH(1,1)*NX1+KTH(2,1)*NY1
 	RC(IK,1) = XK*LL*K_FACE(IK)
 	XK = KTH(1,2)*NX1+KTH(2,2)*NY1
 	RC(IK,2) = XK*LL*K_FACE(IK)
 	
 	K1 = 1; K2 = 0
 	CALL LINE_CAL(X1,Y1,X2,Y2,K1,K2,LLX)
 	NC(IK,1) = LLX/LL
 	K1 = 0; K2 = 1
 	CALL LINE_CAL(X1,Y1,X2,Y2,K1,K2,LLX)
 	NC(IK,2) = LLX/LL
 	
 	XK = NX1*X1+NY1*Y1
 	CELL_V = CELL_V+LL*XK/2.0
 END DO
 
 RNC = 0.0
 DO IK = 1,2
 	DO KK = 1,2
 		DO JK = 1,LINE_NUM
 			RNC(IK,KK) = RNC(IK,KK)+RC(JK,IK)*NC(JK,KK)
 		END DO
 	END DO
 END DO
 
 DO IK = 1,2
 	DO JK = 1,2
 		RNC(IK,JK) = RNC(IK,JK)/CELL_V
 	END DO
 END DO
 
 COE = 0.0
 DO IK = 1,2
 	DO JK = 1,2
 		DO KK = 1,2
 			COE(IK,JK) = COE(IK,JK)+RNC(IK,KK)*RNC(JK,KK)
 		END DO
 	END DO
 END DO
 
 A1 = COE(1,1); A2 = COE(2,2)
 B1 = COE(2,1); B2 = COE(1,2)
 
 
 LAMDA1 = (A1+A2)+SQRT(MAX((A1+A2)**2-4.0*(A1*A2-B1*B2),0.0))
 LAMDA1 = LAMDA1/2.0
 LAMDA2 = (A1+A2)-SQRT(MAX((A1+A2)**2-4.0*(A1*A2-B1*B2),0.0))
 LAMDA2 = LAMDA2/2.0
 
 LAM(1) = SQRT(LAMDA1)
 LAM(2) = SQRT(LAMDA2)
 
 KTH1 = 0.5*(LAM(1)+LAM(2))
 
 END SUBROUTINE 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
